### ISSUE TITLE
How to define an interface only for DNS?

### ISSUE THREAD

**Issue by ypid** [debops/ansible-dnsmasq#13]
Hi

Since #11, my docker containers can not resolve via dnsmasq (on the same system as the containers). I found out that defining the interface docker0 in dnsmasq_interfaces solves the problem but it also enables DHCP options by default. Is there a variable to only enable DNS? `dnsmasq_dhcpv4` seems to be an all or none choice?

```YAML
dnsmasq_interfaces:
  ## Allow DNS queries via docker bridge interface. Also enables DHCP currently.
  - interface: 'docker0'
```
